Repository nuobit/odoo-addons, pull requests merged in 2023-10, with the labels that each got.

#302 [14.0][IMP] account_invoice_report_service: move vat field to left side of …
  account_invoice_report_service/__manifest__.py
  account_invoice_report_service/views/report_invoice_service.xml
Labels: deployed in pro

#297 [14.0][IMP] crm_lost_stage: add lost stage in pipeline
  crm_lost_stage/README.rst
  crm_lost_stage/__init__.py
  crm_lost_stage/__manifest__.py
  crm_lost_stage/data/crm_stage_data.xml
  crm_lost_stage/hooks.py
  crm_lost_stage/i18n/es.po
  crm_lost_stage/models/__init__.py
  crm_lost_stage/models/crm_lead.py
  crm_lost_stage/models/crm_stage.py
  crm_lost_stage/readme/CONTRIBUTORS.rst
  crm_lost_stage/readme/DESCRIPTION.rst
  crm_lost_stage/static/description/icon.png
  crm_lost_stage/static/description/index.html
  crm_lost_stage/views/crm_lead_views.xml
  crm_lost_stage/views/crm_stage_views.xml
  setup/crm_lost_stage/odoo/addons/crm_lost_stage
  setup/crm_lost_stage/setup.py
Labels: deployed in pro

#317 [14.0][IMP] connector_extension_sql: adapter inherit from connector_extension instead of connector
  connector_extension_sql/components/adapter.py
Labels: ready to merge

#316 [16.0][IMP] connector_extension_sql: adapter inherit from connector_extension instead of connector
  connector_extension_sql/components/adapter.py
Labels: ready to merge

#318 [REF] partner_document: move partner_document dims part to dims
  partner_document/__manifest__.py
  partner_document/models/partner_document.py
  partner_document/models/res_partner.py
  partner_document/views/res_partner_views.xml
Labels: ready to merge

#312 [16.0][IMP+FIX] partner_document: allow search expired documents in kanban and tree view & fix domain
  __init__.py
  partner_document/__init__.py
  partner_document/__manifest__.py
  partner_document/models/partner_document.py
  partner_document/security/ir.model.access.csv
  partner_document/static/src/js/kanban_res_partner_button.js
  partner_document/static/src/js/list_res_partner_button.js
  partner_document/static/src/xml/kanban_res_partner_button.xml
  partner_document/static/src/xml/list_res_partner_button.xml
  partner_document/views/res_partner_views.xml
  partner_document/wizard/__init__.py
  partner_document/wizard/partner_document_expired_wizard.py
  partner_document/wizard/partner_document_expired_wizard.xml
Labels: to review

#325 [16.0][IMP] connector_extension: _description created on connector extension external binding
  connector_extension/models/binding/binding.py
Labels: to review

#327 [14.0][FIX] payroll_sage: null process raise an error on update module
  payroll_sage/migrations/14.0.1.0.4/post-migration.py
Labels: to review

#328 [14.0][ADD] base_sparse_field_extension: add extended serialized class
  base_sparse_field_extension/README.rst
  base_sparse_field_extension/__init__.py
  base_sparse_field_extension/__manifest__.py
  base_sparse_field_extension/models/__init__.py
  base_sparse_field_extension/models/fields.py
  base_sparse_field_extension/readme/CONTRIBUTORS.rst
  base_sparse_field_extension/readme/DESCRIPTION.rst
  base_sparse_field_extension/static/description/icon.png
  base_sparse_field_extension/static/description/index.html
  setup/base_sparse_field_extension/odoo/addons/base_sparse_field_extension
  setup/base_sparse_field_extension/setup.py
Labels: to review

#330 [14.0][IMP] connector_sage: update child of payroll sage labour agreement instead of new creation if it already exists
  connector_sage/models/payroll_sage_labour_agreement/mapper.py
Labels: to review
