Repository nuobit/odoo-addons, pull requests merged in 2024-05, with the labels that each got.

#391 [14.0][FIX] connector_oxigesti - fix picking error
  connector_oxigesti/models/__init__.py
  connector_oxigesti/models/sale_order/importer.py
  connector_oxigesti/models/stock_picking.py
Labels: to review

#388 [14.0][FIX] connector_oxigesti: error deleting a variant with binding
  connector_oxigesti/models/product_product/binding.py
  connector_oxigesti/models/product_template/binding.py
Labels: ready to merge, deployed in pro, deployed in pre

#386 [14.0][FIX] stock_rest: enable stock scheduler triggers when creates operation
  stock_rest/services/stock_operation_service.py
Labels: ready to merge, deployed in pro

#374 [14.0][ADD] stock_barcodes_option_new_scan: new module
  setup/stock_barcodes_option_new_scan/odoo/addons/stock_barcodes_option_new_scan
  setup/stock_barcodes_option_new_scan/setup.py
  stock_barcodes_option_new_scan/README.rst
  stock_barcodes_option_new_scan/__init__.py
  stock_barcodes_option_new_scan/__manifest__.py
  stock_barcodes_option_new_scan/readme/CONTRIBUTORS.rst
  stock_barcodes_option_new_scan/readme/DESCRIPTION.rst
  stock_barcodes_option_new_scan/static/description/icon.png
  stock_barcodes_option_new_scan/static/description/index.html
  stock_barcodes_option_new_scan/views/stock_picking_views.xml
Labels: ready to merge, deployed in pro, deployed in pre

#372 [14.0][ADD] stock_barcodes_serial_autoconfirm
  setup/stock_barcodes_serial_autoconfirm/odoo/addons/stock_barcodes_serial_autoconfirm
  setup/stock_barcodes_serial_autoconfirm/setup.py
  stock_barcodes_serial_autoconfirm/README.rst
  stock_barcodes_serial_autoconfirm/__init__.py
  stock_barcodes_serial_autoconfirm/__manifest__.py
  stock_barcodes_serial_autoconfirm/models/__init__.py
  stock_barcodes_serial_autoconfirm/models/stock_barcodes_read_picking.py
  stock_barcodes_serial_autoconfirm/readme/CONTRIBUTORS.rst
  stock_barcodes_serial_autoconfirm/readme/DESCRIPTION.rst
  stock_barcodes_serial_autoconfirm/static/description/icon.png
  stock_barcodes_serial_autoconfirm/static/description/index.html
Labels: ready to merge, deployed in pro, deployed in pre

#350 [14.0][ADD] stock_barcodes_unique_field: new module
  setup/stock_barcodes_unique_field/odoo/addons/stock_barcodes_unique_field
  setup/stock_barcodes_unique_field/setup.py
  stock_barcodes_unique_field/README.rst
  stock_barcodes_unique_field/__init__.py
  stock_barcodes_unique_field/__manifest__.py
  stock_barcodes_unique_field/i18n/es.po
  stock_barcodes_unique_field/models/__init__.py
  stock_barcodes_unique_field/models/stock_barcodes_option.py
  stock_barcodes_unique_field/models/stock_barcodes_read_picking.py
  stock_barcodes_unique_field/readme/CONTRIBUTORS.rst
  stock_barcodes_unique_field/readme/DESCRIPTION.rst
  stock_barcodes_unique_field/static/description/icon.png
  stock_barcodes_unique_field/static/description/index.html
  stock_barcodes_unique_field/views/stock_barcodes_option_view.xml
Labels: ready to merge, deployed in pro, deployed in pre
