Repository nuobit/odoo-addons, pull requests merged in 2024-09, with the labels that each got.

#418 [14.0][UPD] requirements.txt
  connector_ambugest/__manifest__.py
  connector_extension_mssql/README.rst
  connector_extension_mssql/__manifest__.py
  connector_extension_mssql/static/description/index.html
  connector_oxigesti/__manifest__.py
  connector_sage/__manifest__.py
  requirements.txt
Labels: to review

#421 [14.0][IMP] stock_picking_import_serials: improve the field helper
  stock_picking_import_serials/wizard/stock_picking_import_serials.py
Labels: to review

#422 [14.0][IMP] connector_extension: improved resync to force to export all the dependencies once even when dependencies has binding
  connector_extension/components/exporter.py
  connector_extension/models/binding/binding.py
Labels: to review

#423 [16.0][IMP] connector_extension: improved resync to force to export all the dependencies once even when dependencies has binding
  connector_extension/components/exporter.py
  connector_extension/models/binding/binding.py
Labels: to review

#424 [14.0][FIX] account_invoice_report_service: controlled raise of multiple sale orders
  account_invoice_report_service/i18n/ca.po
  account_invoice_report_service/i18n/es.po
  account_invoice_report_service/models/account_invoice.py
Labels: deployed in pro

#420 [14.0][ADD] base_user_update_partner
  base_user_update_partner/README.rst
  base_user_update_partner/__init__.py
  base_user_update_partner/__manifest__.py
  base_user_update_partner/i18n/es.po
  base_user_update_partner/models/__init__.py
  base_user_update_partner/models/res_users.py
  base_user_update_partner/readme/CONTRIBUTORS.rst
  base_user_update_partner/readme/DESCRIPTION.rst
  base_user_update_partner/security/res_groups_security.xml
  base_user_update_partner/static/description/icon.png
  base_user_update_partner/static/description/index.html
  base_user_update_partner/views/res_users_views.xml
  setup/base_user_update_partner/odoo/addons/base_user_update_partner
  setup/base_user_update_partner/setup.py
Labels: deployed in pro, deployed in pre

#411 [17.0][ADD] base_group_internal: New Module
  base_group_internal/README.rst
  base_group_internal/__init__.py
  base_group_internal/__manifest__.py
  base_group_internal/models/__init__.py
  base_group_internal/models/res_groups.py
  base_group_internal/models/res_users.py
  base_group_internal/pyproject.toml
  base_group_internal/readme/CONTRIBUTORS.md
  base_group_internal/readme/DESCRIPTION.md
  base_group_internal/static/description/icon.png
  base_group_internal/static/description/index.html
  base_group_internal/views/res_groups_views.xml
Labels: deployed in pro

#428 [14.0][FIX] connector_oxigesti: fix error with Codigo Articulo allowing modification of the default code
  connector_oxigesti/views/product_product_view.xml
Labels: to review
