Repository nuobit/odoo-addons, pull requests merged in 2024-10, with the labels that each got.

#429 [14.0][ADD] l10n_es_facturae_tax_rounding
  l10n_es_facturae_tax_rounding/README.rst
  l10n_es_facturae_tax_rounding/__init__.py
  l10n_es_facturae_tax_rounding/__manifest__.py
  l10n_es_facturae_tax_rounding/models/__init__.py
  l10n_es_facturae_tax_rounding/models/account_move.py
  l10n_es_facturae_tax_rounding/models/account_tax.py
  l10n_es_facturae_tax_rounding/readme/CONTRIBUTORS.rst
  l10n_es_facturae_tax_rounding/readme/DESCRIPTION.rst
  l10n_es_facturae_tax_rounding/static/description/icon.png
  l10n_es_facturae_tax_rounding/static/description/index.html
  l10n_es_facturae_tax_rounding/views/report_facturae.xml
  setup/l10n_es_facturae_tax_rounding/odoo/addons/l10n_es_facturae_tax_rounding
  setup/l10n_es_facturae_tax_rounding/setup.py
Labels: to review

#436 [14.0][ADD] product_image_removal_required
  product_image_removal_required/README.rst
  product_image_removal_required/__init__.py
  product_image_removal_required/__manifest__.py
  product_image_removal_required/i18n/ca.po
  product_image_removal_required/i18n/es.po
  product_image_removal_required/models/__init__.py
  product_image_removal_required/models/product_image.py
  product_image_removal_required/readme/CONTRIBUTORS.rst
  product_image_removal_required/readme/DESCRIPTION.rst
  product_image_removal_required/static/description/icon.png
  product_image_removal_required/static/description/index.html
  setup/product_image_removal_required/odoo/addons/product_image_removal_required
  setup/product_image_removal_required/setup.py
Labels: to review

#438 [14.0][IMP] account_move_service_report_xlsx: new features
  account_move_service_report_xlsx/i18n/ca_ES.po
  account_move_service_report_xlsx/i18n/es.po
  account_move_service_report_xlsx/models/res_partner_service_report_config.py
  account_move_service_report_xlsx/models/sale_order.py
  account_move_service_report_xlsx/report/report_sale.py
  account_move_service_report_xlsx/views/res_partner_service_report_config_views.xml
Labels: to review

#430 [14.0][FIX] account_move_service: move lines aren't generated when they don't come from a sale order
  account_move_service/models/account_move.py
  account_move_service/models/account_move_line.py
Labels: deployed in pro

#434 [14.0][ADD] project_category_parent_group
  project_category_parent_group/README.rst
  project_category_parent_group/__init__.py
  project_category_parent_group/__manifest__.py
  project_category_parent_group/i18n/es.po
  project_category_parent_group/models/__init__.py
  project_category_parent_group/models/project_project.py
  project_category_parent_group/readme/CONTRIBUTORS.rst
  project_category_parent_group/readme/DESCRIPTION.rst
  project_category_parent_group/static/description/icon.png
  project_category_parent_group/static/description/index.html
  project_category_parent_group/views/project_project_views.xml
  setup/project_category_parent_group/odoo/addons/project_category_parent_group
  setup/project_category_parent_group/setup.py
Labels: ready to merge, deployed in pro, deployed in pre

#433 [14.0][FIX] connector_oxigesti: make Internal Reference mandatory in Produc…
  connector_oxigesti/views/product_product_view.xml
Labels: ready to merge, deployed in pro
