Repository nuobit/odoo-addons, pull requests merged in 2025-05, with the labels that each got.

#570 [16.0][IMP] auth_signup_verify_email_phone: allow resending of email and mobile messages for signup validation
  auth_signup_verify_email_phone/__manifest__.py
  auth_signup_verify_email_phone/controllers/main.py
  auth_signup_verify_email_phone/i18n/ca_ES.po
  auth_signup_verify_email_phone/i18n/es.po
  auth_signup_verify_email_phone/i18n/fr.po
  auth_signup_verify_email_phone/models/__init__.py
  auth_signup_verify_email_phone/models/mail_notification.py
  auth_signup_verify_email_phone/models/mail_template.py
  auth_signup_verify_email_phone/models/res_company.py
  auth_signup_verify_email_phone/models/res_config_settings.py
  auth_signup_verify_email_phone/models/res_partner.py
  auth_signup_verify_email_phone/models/res_users.py
  auth_signup_verify_email_phone/views/res_config_settings.xml
  auth_signup_verify_email_phone/views/res_partner_views.xml
Labels: to review

#574 [16.0][ADD] sale_order_report_zero_qty
  sale_order_report_zero_qty/README.rst
  sale_order_report_zero_qty/__init__.py
  sale_order_report_zero_qty/__manifest__.py
  sale_order_report_zero_qty/models/__init__.py
  sale_order_report_zero_qty/models/sale_order.py
  sale_order_report_zero_qty/readme/CONTRIBUTORS.md
  sale_order_report_zero_qty/readme/DESCRIPTION.md
  sale_order_report_zero_qty/static/description/icon.png
  sale_order_report_zero_qty/static/description/index.html
  sale_order_report_zero_qty/views/report_saleorder_document.xml
  setup/sale_order_report_zero_qty/odoo/addons/sale_order_report_zero_qty
  setup/sale_order_report_zero_qty/setup.py
Labels: to review

#575 [17.0][IMP] barcode_label_template: add format `ean13` in the barcode
  barcode_label_template/models/ir_actions_report.py
  barcode_label_template/models/report_barcode_label_template.py
  barcode_label_template/report/report_label_template.xml
  barcode_label_template/wizard/barcode_label_template_wizard.py
Labels: to review

#576 [16.0][IMP] partner_document: Improve document validation rules
  partner_document/models/partner_document.py
Labels: help wanted, changes requested, needs fixing

#454 [ADD] hr_course_duration
  hr_course_duration/README.rst
  hr_course_duration/__init__.py
  hr_course_duration/__manifest__.py
  hr_course_duration/i18n/es.po
  hr_course_duration/models/__init__.py
  hr_course_duration/models/hr_course.py
  hr_course_duration/readme/CONTRIBUTORS.rst
  hr_course_duration/readme/DESCRIPTION.rst
  hr_course_duration/static/description/icon.png
  hr_course_duration/static/description/index.html
  hr_course_duration/views/hr_course_form_view.xml
  setup/hr_course_duration/odoo/addons/hr_course_duration
  setup/hr_course_duration/setup.py
Labels: ready to merge, deployed in pro

#447 [14.0][IMP] l10n_es_aeat_mod303_special_prorate: add prorate taxes to new 2024-10 version
  l10n_es_aeat_mod303_special_prorate/__manifest__.py
  l10n_es_aeat_mod303_special_prorate/data/tax_code_map_mod303_202410_data.xml
Labels: ready to merge, deployed in pro
